import React from 'react';

const HomePage = () => {
    return (
        <div>
            <h1>Home</h1>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam nec urna blandit, vulputate augue et, sodales mauris. Donec augue sapien, maximus ac pulvinar ultrices, dignissim sit amet erat. Sed et ipsum ut enim mattis hendrerit eget a ex. Donec velit mauris, facilisis in augue at, ultricies faucibus sem. Pellentesque mattis risus sapien, ac auctor lorem ullamcorper eget. Fusce vulputate fringilla dolor sollicitudin bibendum. Pellentesque quis lorem at dui iaculis dictum ac quis turpis. Nam blandit imperdiet enim sit amet blandit. Cras ultrices massa aliquam pharetra tincidunt. Aliquam vestibulum purus quis urna vestibulum feugiat. Aliquam lacus mi, condimentum vitae sapien venenatis, rutrum semper ex. Proin ut diam dictum, faucibus enim non, gravida eros. Nulla varius lacus augue, id volutpat risus vestibulum at.

In ut tortor in ante blandit blandit eu et neque. Nullam tincidunt enim ex, in pharetra enim ultricies sed. Morbi id lectus fermentum, tincidunt elit quis, aliquam nisl. Nam volutpat dolor quis nibh imperdiet, id mollis justo placerat. Vestibulum hendrerit orci ut nisl porta, quis vehicula leo pretium. Mauris feugiat massa eu porttitor bibendum. Etiam pretium auctor fermentum. Integer sem elit, sagittis ut tincidunt in, porta at purus. Donec eget ultrices nulla.

Proin quis neque tristique, volutpat enim commodo, aliquam massa. Praesent congue pellentesque eros, eget pharetra ipsum iaculis ut. Vestibulum convallis enim dapibus ante pharetra, vel bibendum eros pulvinar. Etiam non nulla augue. Quisque a dui posuere mauris imperdiet egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eu orci sed elit commodo blandit non in mauris. Maecenas vehicula justo sit amet urna fringilla tristique. In sit amet pharetra augue. Maecenas nunc quam, venenatis vitae lacus at, gravida ornare felis. Pellentesque id erat molestie, porta ante vitae, ornare leo. Vivamus aliquet laoreet elit, at lobortis mi consequat non. Cras finibus, felis id vulputate feugiat, nibh lectus viverra ex, id aliquam augue ex ac elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus sed urna sed justo suscipit rutrum eu sed lacus. Sed ac sem pretium, fermentum ipsum nec, iaculis nisl.

Cras diam metus, ornare vitae consequat ac, scelerisque at enim. Ut vel elit at turpis suscipit euismod a sed felis. Quisque blandit augue convallis, mattis velit in, tincidunt est. Integer vitae dui nec enim facilisis cursus id non nisl. Donec pharetra semper neque sit amet finibus. Nunc at congue ligula, id interdum mi. Cras vestibulum augue massa, vel molestie enim eleifend ut. Mauris sit amet velit dignissim erat ornare auctor. Phasellus et ullamcorper felis. Maecenas augue enim, cursus eu purus euismod, ullamcorper suscipit sapien. Maecenas at suscipit massa, eget viverra tellus. Pellentesque quis elit id tellus feugiat ultrices. Quisque in nisi nec massa convallis aliquam. Sed ultrices nulla ut facilisis efficitur. In tempus, urna et tincidunt commodo, ante neque porta enim, nec tempor nibh augue quis ligula.

In hac habitasse platea dictumst. Maecenas mollis, mi at accumsan egestas, justo sem finibus mauris, eget porta augue ante a nibh. Maecenas et rhoncus urna. Praesent ligula eros, semper imperdiet consectetur vel, fermentum a risus. Morbi posuere odio sed tempus convallis. Aliquam eleifend molestie nibh ut posuere. Aliquam bibendum semper accumsan. Donec dui turpis, iaculis in mattis vitae, pretium in ex. Integer at rhoncus dolor, eget ornare nibh. Aliquam iaculis porttitor sagittis. Sed malesuada sem sed mauris mollis porttitor. Donec sit amet rutrum arcu. Etiam facilisis ligula massa, ut dignissim ante faucibus eget. Duis vitae dui volutpat ligula eleifend accumsan. Ut non semper dui.
        </div>
    );
};

export default HomePage;